sudo: required

language: generic

services:
  - docker

before_install:


after_success:
  


before_deploy:
  - zip -r rudder-server .
  - mkdir -p deploy
  - mv rudder-server.zip deploy/rudder-server.zip
  - echo "Before deploy success"

deploy:
  - provider: s3
    bucket: $AWS_S3_BUCKET_NAME
    region: $AWS_LIGHT_SAIL_REGION
    local_dir: deploy
    skip_cleanup: true
    wait_until_deploy: true
    access_key_id: $AWS_ACCESS_KEY_S3
    secret_access_key: $AWS_SECRET_ACCESS_KEY_S3
    on:
      branch: $BRANCH_NAME
    

      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_CODE_DEPLOY
    secret_access_key: $AWS_SECRET_ACCESS_KEY_CODE_DEPLOY
    bucket: $AWS_S3_BUCKET_NAME
    key: rudder-server.zip
    bundle_type: zip
    application: rudder-codedeploy-app
    deployment_group: rudder-codedeploy-group
    region: $AWS_LIGHT_SAIL_REGION
    wait_until_deployed : true
    on:
      branch: $BRANCH_NAME

notificaitons:
  email:
    recipients:
      - lsjpjs1@naver.com
