sudo: required

language: generic

services:
  - docker

before_install:


after_success:
  

before_deploy:
  - zip -r rudder-server .
  - mkdir -p deploy
  - mv rudder-server.zip deploy/rudder-server.zip
  - echo "Before deploy success"

deploy:
  - provider: s3
    bucket: rudder-docker
    region: $AWS_LIGHT_SAIL_REGION
    local_dir: deploy
    skip_cleanup: true
    wait_until_deploy: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
      branch: master
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: rudder-docker
    key: rudder-server.zip
    bundle_type: zip
    application: rudder-codedeploy-app
    deployment_group: rudder-codedeploy-group
    region: $AWS_LIGHT_SAIL_REGION
    wait_until_deployed : true
    on:
      branch: master


notificaitons:
  email:
    recipients:
      - lsjpjs1@naver.com
