version: 0.0
os: linux
files:
  - source: /
    destination: /home/rudder-docker
  
permissions:
  - object: /
    pattern: "**"
    owner: bitnami
    group: bitnami
  
hooks:
  ApplicationStart:
    - location: /deploy.sh
      timeout: 100
      runas: bitnami
